### PR TITLE
core/opregion.c: Handle multibyte IndexFields properly

### LINKED ISSUE #55: Refactor IndexField() I/O
IndexField() I/O is known to be broken. Refactor it.

### PR DESCRIPTION
**Pull request by thomtl**
Closes #55 
Do not merge yet, requires more testing on real hardware

### CODE REVIEW

File: core/exec.c [hunk 1]
```diff
@@ -2982,9 +2982,9 @@ static lai_api_error_t lai_exec_parse(int parse_mode, lai_state_t *state) {
                         node->type = LAI_NAMESPACE_INDEXFIELD;
                         node->idxf_index_node = index_node;
                         node->idxf_data_node = data_node;
-                        node->idxf_flags = access_type;
-                        node->idxf_size = skip_bits;
-                        node->idxf_offset = curr_off;
+                        node->fld_flags = access_type;
+                        node->fld_size = skip_bits;
+                        node->fld_offset = curr_off;
```
Comment (avdgrinten) [inline core/exec.c:2987]: This looks broken, we're using both `idxf_` and `fld_` fields even though they belong to different union members.

Comment (avdgrinten) [reply core/exec.c:2987]: Ah, the union members are actually unified by this commit. Then I'd suggest to rename `idxf_` to `fld_`.
